server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0

cors:
  allowed-origin: ${ALLOWED_ORIGIN}

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
    defer-datasource-initialization: ${SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION:true}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
